/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adatbáziskliens;

import adatbáziskapcsolat.DbKapcsolat;
import javax.swing.JFrame;

/**
 *
 * @author kicsi
 */
public class Keszletnyilvantarto extends javax.swing.JFrame {

    /**
     * Creates new form Keszletnyilvantarto
     */
    public Keszletnyilvantarto() {
        initComponents();
        this.setLocationRelativeTo(null);
        db = new DbKapcsolat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        ujTermekMenu = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        ujRakterMenu = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        ujVevoMenu = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        ujBeszallitoMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Készletnyilvántartó");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Termék");

        ujTermekMenu.setText("Új Termék Hozzáadás");
        ujTermekMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ujTermekMenuActionPerformed(evt);
            }
        });
        jMenu3.add(ujTermekMenu);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Raktár");

        ujRakterMenu.setText("Új Raktár Hozzáadás");
        ujRakterMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ujRakterMenuActionPerformed(evt);
            }
        });
        jMenu4.add(ujRakterMenu);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Vevő");

        ujVevoMenu.setText("Új Vevő Hozzáadás");
        ujVevoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ujVevoMenuActionPerformed(evt);
            }
        });
        jMenu5.add(ujVevoMenu);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Beszállító");

        ujBeszallitoMenu.setText("Új Beszállító Hozzáadás");
        ujBeszallitoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ujBeszallitoMenuActionPerformed(evt);
            }
        });
        jMenu6.add(ujBeszallitoMenu);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ujBeszallitoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ujBeszallitoMenuActionPerformed
        this.setVisible(false);
        UjBeszallitoHozzaadas ujBeszallito=new UjBeszallitoHozzaadas(this,true);
        ujBeszallito.setVisible(true);
    }//GEN-LAST:event_ujBeszallitoMenuActionPerformed

    private void ujTermekMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ujTermekMenuActionPerformed
        this.setVisible(false);
        UjTermekHozzaadas ujTermek = new UjTermekHozzaadas(this, true);
        ujTermek.setVisible(true);

    }//GEN-LAST:event_ujTermekMenuActionPerformed

    private void ujRakterMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ujRakterMenuActionPerformed
        this.setVisible(false);
        UjRaktarHozzaadas ujRaktar = new UjRaktarHozzaadas(this, true);
        ujRaktar.setVisible(true);

    }//GEN-LAST:event_ujRakterMenuActionPerformed

    private void ujVevoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ujVevoMenuActionPerformed
        this.setVisible(false);
        UjVevoHozzaadas ujVevo= new UjVevoHozzaadas(this,true);
        ujVevo.setVisible(true);
    }//GEN-LAST:event_ujVevoMenuActionPerformed

    protected DbKapcsolat getDbKapcsolat() {
        return db;
    }
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Keszletnyilvantarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Keszletnyilvantarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Keszletnyilvantarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Keszletnyilvantarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Keszletnyilvantarto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem ujBeszallitoMenu;
    private javax.swing.JMenuItem ujRakterMenu;
    private javax.swing.JMenuItem ujTermekMenu;
    private javax.swing.JMenuItem ujVevoMenu;
    // End of variables declaration//GEN-END:variables
    private DbKapcsolat db;
    
}
