
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import newpackage.Beszállító;
import newpackage.DbKapcsolat;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kicsi
 */
public class BeszallitoHozzaad extends javax.swing.JPanel {

    private DbKapcsolat db;

    public BeszallitoHozzaad() {
        initComponents();
        modositGomb.setVisible(false);
        radioGombok.add(hozzaadRadioGomb);
        radioGombok.add(modositRadioGomb);
        radioGombok.add(torolRadioGomb);

        hozzaadRadioGomb.setSelected(true);
        db = frame.getDbKapcsolat();

        beszallitolista.setEnabled(false);
        // AutoCompleteDecorator.decorate(beszallitoLista);
        AutoCompleteDecorator.decorate(beszallitolista);
        // beszallitolista.addItem("valami");
        // beszallitoLista.setModel(new DefaultComboBoxModel(db.getBeszallitok()));
        beszallitolista.setModel(new DefaultComboBoxModel(db.getBeszallitok()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        radioGombok = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        keszGomb = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        hozzaadRadioGomb = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        nev = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        telephely = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        telefonszam = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        adoszam = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        modositRadioGomb = new javax.swing.JRadioButton();
        torolRadioGomb = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        beszallitolista = new javax.swing.JComboBox();
        keresGomb = new javax.swing.JButton();
        modositGomb = new javax.swing.JButton();

        setBackground(new java.awt.Color(238, 238, 238));
        setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 140, 113));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Beszállító műveletek");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        keszGomb.setBackground(new java.awt.Color(255, 140, 0));
        keszGomb.setForeground(new java.awt.Color(255, 255, 255));
        keszGomb.setText("KÉSZ");
        keszGomb.setBorder(null);
        keszGomb.setBorderPainted(false);
        keszGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keszGombActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        hozzaadRadioGomb.setBackground(new java.awt.Color(255, 255, 255));
        hozzaadRadioGomb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        hozzaadRadioGomb.setForeground(new java.awt.Color(0, 140, 113));
        hozzaadRadioGomb.setText("Új beszállító hozzáadása");
        hozzaadRadioGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hozzaadRadioGombActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 140, 113));
        jLabel2.setText("Név:");

        nev.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        nev.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EnterKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 140, 113));
        jLabel3.setText("Telephely:");

        telephely.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        telephely.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EnterKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 140, 113));
        jLabel9.setText("Telefonszám:");

        telefonszam.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        telefonszam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EnterKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 140, 113));
        jLabel10.setText("E-mail cím:");

        email.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EnterKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 140, 113));
        jLabel11.setText("Adószám:");

        adoszam.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        adoszam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EnterKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telephely, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefonszam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adoszam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hozzaadRadioGomb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nev, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(hozzaadRadioGomb)
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(telephely, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(telefonszam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(adoszam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        modositRadioGomb.setBackground(new java.awt.Color(255, 255, 255));
        modositRadioGomb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        modositRadioGomb.setForeground(new java.awt.Color(0, 140, 113));
        modositRadioGomb.setText("Beszállító adatmódosítás");
        modositRadioGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modositRadioGombActionPerformed(evt);
            }
        });

        torolRadioGomb.setBackground(new java.awt.Color(255, 255, 255));
        torolRadioGomb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        torolRadioGomb.setForeground(new java.awt.Color(0, 140, 113));
        torolRadioGomb.setText("Beszállító törlés");
        torolRadioGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torolRadioGombActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 140, 113));
        jLabel4.setText("Beszállító:");

        beszallitolista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beszallitoListaActionPerformed(evt);
            }
        });

        keresGomb.setBackground(new java.awt.Color(255, 140, 0));
        keresGomb.setForeground(new java.awt.Color(255, 255, 255));
        keresGomb.setText("FRISSÍT");
        keresGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keresGombActionPerformed(evt);
            }
        });

        modositGomb.setBackground(new java.awt.Color(255, 140, 0));
        modositGomb.setForeground(new java.awt.Color(255, 255, 255));
        modositGomb.setText("TERMÉK MÓDOSÍTÁS");
        modositGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modositGombActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(modositGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(modositRadioGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(158, 158, 158)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(beszallitolista, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(torolRadioGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(keresGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modositRadioGomb)
                    .addComponent(torolRadioGomb))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(beszallitolista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(keresGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(modositGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(keszGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(keszGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void keszGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keszGombActionPerformed

        try {
            Beszállító kijeloltBeszallito = (Beszállító) beszallitolista.getSelectedItem();
            String nev_ = nev.getText();
            String telephely_ = telephely.getText();
            String telefonszam_ = telefonszam.getText();
            String email_ = email.getText();
            String adoszam_ = adoszam.getText();

            if (hozzaadRadioGomb.isSelected() && !nev_.equals("DEFAULT") || (modositRadioGomb.isSelected() && !kijeloltBeszallito.getCegNev().equals("DEFAULT"))) {

                if (nev_.equals("") || telephely_.equals("") || email_.equals("")) {
                    JOptionPane.showMessageDialog(null, "A név, telephely, e-mail cím megadása kötelező!");
                    return;
                }
                if (telefonszam_.length() < 11 || telefonszam_.length() > 12 || telefonszam_.charAt(0) != '+' || telefonszam_.charAt(1) != '3' || telefonszam_.charAt(2) != '6') {
                    JOptionPane.showMessageDialog(null, "Telefoszám formátum +36202222222");
                    return;
                }
                if (!(email_.contains("@") && email_.contains("."))) {
                    JOptionPane.showMessageDialog(null, "Hibás e-mail cím!");
                    return;
                }
                if (adoszam_.length() != 13 || adoszam_.charAt(8) != '-' || adoszam_.charAt(10) != '-') {
                    JOptionPane.showMessageDialog(null, "Adószám: XXXXXXXX-X-XX");
                    return;
                }
                try {
                    String adoszamEll = adoszam_.substring(0, 8);
                    int ellenőrzés = Integer.parseInt(adoszamEll);
                    adoszamEll = adoszam_.substring(9, 10);
                    ellenőrzés = Integer.parseInt(adoszamEll);
                    adoszamEll = adoszam_.substring(11, 13);
                    ellenőrzés = Integer.parseInt(adoszamEll);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "!!!Adószám: XXXXXXXX-X-XX");
                    return;
                }

            }

            Beszállító ujbeszallito = new Beszállító(nev_, telephely_, telefonszam_, email_, adoszam_);

            if (hozzaadRadioGomb.isSelected()) {
                try {
                    db.ujBeszallito(ujbeszallito);

                    beszallitolista.setModel(new DefaultComboBoxModel(db.getBeszallitok()));
                    
                    JOptionPane.showMessageDialog(null, "Beszállító hozzáadva!");
                } catch (Exception ex) {
                    Logger.getLogger(DbKapcsolat.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Hiba");
                }
            }
            if (modositRadioGomb.isSelected()) {
                Beszállító modositandoBeszallito = (Beszállító) beszallitolista.getSelectedItem();
                int modositandoBeszallitoId = modositandoBeszallito.getCegId();
                ujbeszallito.setCegId(modositandoBeszallitoId);
                db.modositBeszallito(ujbeszallito);

                beszallitolista.setModel(new DefaultComboBoxModel(db.getBeszallitok()));
                keresGomb.doClick();
                System.out.println("1");
            }
            if (torolRadioGomb.isSelected()) {
                Beszállító torlendoBeszallito = (Beszállító) beszallitolista.getSelectedItem();
                db.torolBeszallito(torlendoBeszallito);

                beszallitolista.setModel(new DefaultComboBoxModel(db.getBeszallitok()));
                keresGomb.doClick();
                System.out.println("2");
            }

        } catch (Exception e) {
            if (hozzaadRadioGomb.isSelected() || modositRadioGomb.isSelected()) {
                JOptionPane.showMessageDialog(null, "Hibás adatbevitel!");
            }
            if (torolRadioGomb.isSelected()) {
                JOptionPane.showMessageDialog(null, "A beszállító nem törölhető amíg termékek tartoznak hozzá! Módosítsa vagy törölje a termékek adatait");
                Beszállító kivalasztottBeszallito = (Beszállító) beszallitolista.getSelectedItem();
                CsoportosBeszallitoModositas modositas = new CsoportosBeszallitoModositas(null, true, kivalasztottBeszallito);
                modositas.setVisible(true);
            }
        }

    }//GEN-LAST:event_keszGombActionPerformed

    private void hozzaadRadioGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hozzaadRadioGombActionPerformed
        nev.setEditable(true);
        nev.setBackground(Color.WHITE);
        telephely.setEditable(true);
        telephely.setBackground(Color.WHITE);
        telefonszam.setEditable(true);
        telefonszam.setBackground(Color.WHITE);
        email.setEditable(true);
        email.setBackground(Color.WHITE);
        adoszam.setEditable(true);
        adoszam.setBackground(Color.WHITE);
        beszallitolista.setEnabled(false);

        modositGomb.setVisible(false);

        nev.setText("");
        telephely.setText("");
        telefonszam.setText("");
        email.setText("");
        adoszam.setText("");
    }//GEN-LAST:event_hozzaadRadioGombActionPerformed

    private void modositRadioGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modositRadioGombActionPerformed
        nev.setEditable(true);
        nev.setBackground(Color.WHITE);
        telephely.setEditable(true);
        telephely.setBackground(Color.WHITE);
        telefonszam.setEditable(true);
        telefonszam.setBackground(Color.WHITE);
        email.setEditable(true);
        email.setBackground(Color.WHITE);
        adoszam.setEditable(true);
        adoszam.setBackground(Color.WHITE);
        beszallitolista.setEnabled(true);

        modositGomb.setVisible(true);

        keresGomb.doClick();

    }//GEN-LAST:event_modositRadioGombActionPerformed

    private void torolRadioGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torolRadioGombActionPerformed
        nev.setEditable(false);
        nev.setBackground(Color.LIGHT_GRAY);
        telephely.setEditable(false);
        telephely.setBackground(Color.LIGHT_GRAY);
        telefonszam.setEditable(false);
        telefonszam.setBackground(Color.LIGHT_GRAY);
        email.setEditable(false);
        email.setBackground(Color.LIGHT_GRAY);
        adoszam.setEditable(false);
        adoszam.setBackground(Color.LIGHT_GRAY);
        beszallitolista.setEnabled(true);

        modositGomb.setVisible(false);

        keresGomb.doClick();

    }//GEN-LAST:event_torolRadioGombActionPerformed

    private void keresGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keresGombActionPerformed

        if (modositRadioGomb.isSelected()) {
            try {
                Beszállító beszallito = (Beszállító) beszallitolista.getSelectedItem();
                nev.setText(beszallito.getCegNev());
                telephely.setText(beszallito.getTelephely());
                email.setText(beszallito.getCegEmailCim());
                adoszam.setText(beszallito.getCegAdoSzam());
                telefonszam.setText(beszallito.getCegTelefonSzam());

                nev.setEditable(true);
                nev.setBackground(Color.WHITE);
                telephely.setEditable(true);
                telephely.setBackground(Color.WHITE);
                telefonszam.setEditable(true);
                telefonszam.setBackground(Color.WHITE);
                email.setEditable(true);
                email.setBackground(Color.WHITE);
                adoszam.setEditable(true);
                adoszam.setBackground(Color.WHITE);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Beszállító lista üres!");
            }
        }
        if (torolRadioGomb.isSelected()) {
            try {

                Beszállító beszallito = (Beszállító) beszallitolista.getSelectedItem();
                nev.setText(beszallito.getCegNev());
                telephely.setText(beszallito.getTelephely());
                email.setText(beszallito.getCegEmailCim());
                adoszam.setText(beszallito.getCegAdoSzam());
                telefonszam.setText(beszallito.getCegTelefonSzam());

                nev.setEditable(false);
                nev.setBackground(Color.LIGHT_GRAY);
                telephely.setEditable(false);
                telephely.setBackground(Color.LIGHT_GRAY);
                telefonszam.setEditable(false);
                telefonszam.setBackground(Color.LIGHT_GRAY);
                email.setEditable(false);
                email.setBackground(Color.LIGHT_GRAY);
                adoszam.setEditable(false);
                adoszam.setBackground(Color.LIGHT_GRAY);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Beszállító lista üres!");
            }
        }
    }//GEN-LAST:event_keresGombActionPerformed

    private void modositGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modositGombActionPerformed
        Beszállító kivalasztottBeszallito = (Beszállító) beszallitolista.getSelectedItem();
        CsoportosBeszallitoModositas modositas = new CsoportosBeszallitoModositas(null, true, kivalasztottBeszallito);
        modositas.setVisible(true);
    }//GEN-LAST:event_modositGombActionPerformed

    private void EnterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EnterKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            keszGomb.doClick();
        }
    }//GEN-LAST:event_EnterKeyPressed

    private void beszallitoListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beszallitoListaActionPerformed
        if (modositRadioGomb.isSelected() || torolRadioGomb.isSelected()) {
            keresGomb.doClick();
            System.out.println("5");
        }
    }//GEN-LAST:event_beszallitoListaActionPerformed
    public JComboBox getBeszallitoComboBox() {
        return this.beszallitolista;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adoszam;
    private javax.swing.JComboBox beszallitolista;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton hozzaadRadioGomb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton keresGomb;
    private javax.swing.JButton keszGomb;
    private javax.swing.JButton modositGomb;
    private javax.swing.JRadioButton modositRadioGomb;
    private javax.swing.JTextField nev;
    private javax.swing.ButtonGroup radioGombok;
    private javax.swing.JTextField telefonszam;
    private javax.swing.JTextField telephely;
    private javax.swing.JRadioButton torolRadioGomb;
    // End of variables declaration//GEN-END:variables
}
