
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import newpackage.DbKapcsolat;
import newpackage.Raktár;
import newpackage.Termék;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kicsi
 */
public class BevetelKivetel extends javax.swing.JPanel {

    private DbKapcsolat db;
    private Raktár raktar;
    private int raktarId;
    private Termék termek;
    private String termekMegnevezes;
    private String termekCikkszam;

    public BevetelKivetel() {
        initComponents();
        db = frame.getDbKapcsolat();
        raktarLista.setModel(new DefaultComboBoxModel(db.getRaktarak()));
        termekLista.setModel(new DefaultComboBoxModel(db.getTermekek()));

        Object raktarEllenorzes = raktarLista.getSelectedItem();
        Object termekEllenorzes = termekLista.getSelectedItem();

        if (raktarEllenorzes != null && termekEllenorzes != null) {
            this.raktar = (Raktár) raktarLista.getSelectedItem();
            this.raktarId = raktar.getRaktarId();
            this.termek = (Termék) termekLista.getSelectedItem();
            this.termekMegnevezes = termek.getMegnevezes();
            this.termekCikkszam = termek.getCikkszam();

            tabla.setModel(db.lekerdezes(raktarId, termekMegnevezes, termekCikkszam));
        }
        
        JTableHeader header = tabla.getTableHeader(); //[255,140,0]
        header.setBackground(Color.getHSBColor((float) 0.46785712, (float) 1.0, (float) 0.54901963));
        header.setForeground(Color.WHITE);
        float[] hsbvals = new float[3];
        Color.RGBtoHSB(0, 140, 113, hsbvals);
        System.out.println(hsbvals[0] + " " + hsbvals[1] + " " + hsbvals[2]);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tabla.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        tabla.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        tabla.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        raktarLista = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        termekLista = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        termekDb = new javax.swing.JTextField();
        bevetelezes = new javax.swing.JButton();
        kivetelezes = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        jPanel2.setBackground(new java.awt.Color(238, 238, 238));

        jPanel1.setBackground(new java.awt.Color(0, 140, 113));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Termék bevételezés, termék kivét");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 140, 113));
        jLabel5.setText("Raktár kiválasztása:");

        raktarLista.setEditable(true);
        raktarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raktarListaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 140, 113));
        jLabel3.setText("Termék kiválasztása:");

        termekLista.setEditable(true);
        termekLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termekListaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 140, 113));
        jLabel6.setText("Mennyiség megadása:");

        termekDb.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        bevetelezes.setBackground(new java.awt.Color(255, 140, 0));
        bevetelezes.setForeground(new java.awt.Color(255, 255, 255));
        bevetelezes.setText("BEVÉTELEZÉS");
        bevetelezes.setBorderPainted(false);
        bevetelezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bevetelezesActionPerformed(evt);
            }
        });

        kivetelezes.setBackground(new java.awt.Color(255, 140, 0));
        kivetelezes.setForeground(new java.awt.Color(255, 255, 255));
        kivetelezes.setText("KIVÉTELEZÉS");
        kivetelezes.setToolTipText("");
        kivetelezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kivetelezesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(bevetelezes, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kivetelezes, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(termekLista, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(raktarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(termekDb, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(raktarLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(termekLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(termekDb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kivetelezes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bevetelezes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 140, 113));
        jLabel2.setText("Aktuális készlet:");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(383, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void kivetelezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kivetelezesActionPerformed
        try {
            int raktarId = ((Raktár) raktarLista.getSelectedItem()).getRaktarId();
            int termekId = ((Termék) termekLista.getSelectedItem()).getTermekId();
            int darab = Integer.parseInt(termekDb.getText());

            if (db.kivételezés(raktarId, termekId, darab)) {
                JOptionPane.showMessageDialog(null, "Termék kivételezve");
            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Hibás adatbevitel!");
        }
        this.raktar = (Raktár) raktarLista.getSelectedItem();
        this.raktarId = raktar.getRaktarId();
        this.termek = (Termék) termekLista.getSelectedItem();
        this.termekMegnevezes = termek.getMegnevezes();
        this.termekCikkszam = termek.getCikkszam();

        tabla.setModel(db.lekerdezes(raktarId, termekMegnevezes, termekCikkszam));
        termekDb.setText("");
    }//GEN-LAST:event_kivetelezesActionPerformed

    private void bevetelezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bevetelezesActionPerformed
        try {
            int raktarId = ((Raktár) raktarLista.getSelectedItem()).getRaktarId();
            int termekId = ((Termék) termekLista.getSelectedItem()).getTermekId();
            int darab = Integer.parseInt(termekDb.getText());

            db.bevetelezes(raktarId, termekId, darab);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Hibás adatbevitel!");
        }
        this.raktar = (Raktár) raktarLista.getSelectedItem();
        this.raktarId = raktar.getRaktarId();
        this.termek = (Termék) termekLista.getSelectedItem();
        this.termekMegnevezes = termek.getMegnevezes();
        this.termekCikkszam = termek.getCikkszam();

        tabla.setModel(db.lekerdezes(raktarId, termekMegnevezes, termekCikkszam));
        termekDb.setText("");
    }//GEN-LAST:event_bevetelezesActionPerformed

    private void termekListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termekListaActionPerformed
        Object ellenorzes = termekLista.getSelectedItem();

        if (ellenorzes != null) {
            this.raktar = (Raktár) raktarLista.getSelectedItem();
            this.raktarId = raktar.getRaktarId();
            this.termek = (Termék) termekLista.getSelectedItem();
            this.termekMegnevezes = termek.getMegnevezes();
            this.termekCikkszam = termek.getCikkszam();

            tabla.setModel(db.lekerdezes(raktarId, termekMegnevezes, termekCikkszam));
        }
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tabla.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        tabla.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        tabla.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);

    }//GEN-LAST:event_termekListaActionPerformed

    private void raktarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raktarListaActionPerformed
        Object ellenorzes = raktarLista.getSelectedItem();

        if (ellenorzes != null) {
            this.raktar = (Raktár) raktarLista.getSelectedItem();
            this.raktarId = raktar.getRaktarId();
            this.termek = (Termék) termekLista.getSelectedItem();
            this.termekMegnevezes = termek.getMegnevezes();
            this.termekCikkszam = termek.getCikkszam();

            tabla.setModel(db.lekerdezes(raktarId, termekMegnevezes, termekCikkszam));
        }
    }//GEN-LAST:event_raktarListaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bevetelezes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kivetelezes;
    private javax.swing.JComboBox raktarLista;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField termekDb;
    private javax.swing.JComboBox termekLista;
    // End of variables declaration//GEN-END:variables
}
