
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import newpackage.Beszállító;
import newpackage.DbKapcsolat;
import newpackage.Termék;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kicsi
 */
public class CsoportosBeszallitoModositas extends javax.swing.JDialog {

    private DbKapcsolat db;
    private Beszállító beszallito = null;

    public CsoportosBeszallitoModositas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        JTableHeader header = table.getTableHeader(); //[255,140,0]
        header.setBackground(Color.getHSBColor((float) 0.46785712, (float) 1.0, (float) 0.54901963));
        header.setForeground(Color.WHITE);
        float[] hsbvals = new float[3];
        Color.RGBtoHSB(0, 140, 113, hsbvals);
        System.out.println(hsbvals[0] + " " + hsbvals[1] + " " + hsbvals[2]);

    }

    public CsoportosBeszallitoModositas(java.awt.Frame parent, boolean modal, Beszállító beszallito) {
        super(parent, modal);
        initComponents();
        AutoCompleteDecorator.decorate(beszallitoLista);
        this.setLocationRelativeTo(null);
        // table.setModel(model);
        db = frame.getDbKapcsolat();
        beszallitoLista.setModel(new DefaultComboBoxModel(db.getBeszallitok()));
        this.beszallito = beszallito;
        table.setModel(db.lekerdezBeszallitoTermekeik(beszallito));
        beszallitoNeve.setText(beszallito.getCegNev());

        JTableHeader header = table.getTableHeader(); //[255,140,0]
        header.setBackground(Color.getHSBColor((float) 0.46785712, (float) 1.0, (float) 0.54901963));
        header.setForeground(Color.WHITE);
        float[] hsbvals = new float[3];
        Color.RGBtoHSB(0, 140, 113, hsbvals);
        System.out.println(hsbvals[0] + " " + hsbvals[1] + " " + hsbvals[2]);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        table.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        table.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        modositGomb = new javax.swing.JButton();
        beszallitoLista = new javax.swing.JComboBox();
        torol = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        beszallitoNeve = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Beszállító Termék Módosítás");
        setBackground(new java.awt.Color(238, 238, 238));

        table.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(table);

        modositGomb.setBackground(new java.awt.Color(255, 140, 0));
        modositGomb.setForeground(new java.awt.Color(255, 255, 255));
        modositGomb.setText("MÓDOSÍT");
        modositGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modositGombActionPerformed(evt);
            }
        });

        torol.setBackground(new java.awt.Color(255, 140, 0));
        torol.setForeground(new java.awt.Color(255, 255, 255));
        torol.setText("TÖRÖL");
        torol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torolActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 140, 113));
        jLabel1.setText("Új beszállító kiválasztása");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 140, 113));
        jLabel2.setText("Beszállítóhoz rendelt termékek:");

        beszallitoNeve.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        beszallitoNeve.setForeground(new java.awt.Color(0, 140, 113));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(modositGomb)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(46, 46, 46)
                                .addComponent(beszallitoLista, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(338, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(beszallitoNeve, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(torol, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(beszallitoNeve, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(torol, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beszallitoLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modositGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modositGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modositGombActionPerformed
        for (int i = 0; i < table.getRowCount(); ++i) {
            if ((Boolean) table.getValueAt(i, 3)) {
                String cikkszam = (String) table.getValueAt(i, 0);
                int termekId = ((Termék) db.lekerdezTermek(cikkszam)).getTermekId();
                Beszállító beszallito = (Beszállító) beszallitoLista.getSelectedItem();
                db.modositTermekBeszallito(termekId, beszallito.getCegId());

            }

        }
        table.setModel(db.lekerdezBeszallitoTermekeik(beszallito));
        JOptionPane.showMessageDialog(rootPane, "Beszállító módosítva!");
    }//GEN-LAST:event_modositGombActionPerformed

    private void torolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torolActionPerformed
        for (int i = 0; i < table.getRowCount(); ++i) {
            if ((Boolean) table.getValueAt(i, 3)) {
                String cikkszam = (String) table.getValueAt(i, 0);
                int termekId = ((Termék) db.lekerdezTermek(cikkszam)).getTermekId();
                // Beszállító beszallito=(Beszállító) beszallitoLista.getSelectedItem();
                db.torolTermekBeszallito(termekId);

            }

        }
        table.setModel(db.lekerdezBeszallitoTermekeik(beszallito));
        JOptionPane.showMessageDialog(rootPane, "A termékek adatai megváltoztak!");
    }//GEN-LAST:event_torolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CsoportosBeszallitoModositas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CsoportosBeszallitoModositas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CsoportosBeszallitoModositas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CsoportosBeszallitoModositas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CsoportosBeszallitoModositas dialog = new CsoportosBeszallitoModositas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox beszallitoLista;
    private javax.swing.JLabel beszallitoNeve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modositGomb;
    private javax.swing.JTable table;
    private javax.swing.JButton torol;
    // End of variables declaration//GEN-END:variables
}
