
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import newpackage.DbKapcsolat;
import newpackage.Raktár;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kicsi
 */
public class RaktarHozzaad extends javax.swing.JPanel {

    private DbKapcsolat db;

    public RaktarHozzaad() {
        db = frame.getDbKapcsolat();
        initComponents();
        radioGombok.add(hozzaadRadioGomb);
        radioGombok.add(modositRadioGomb);
        radioGombok.add(torolRadioGomb);

        hozzaadRadioGomb.setSelected(true);

        raktarLista.setEnabled(false);

        AutoCompleteDecorator.decorate(raktarLista);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGombok = new javax.swing.ButtonGroup();
        KeszGomb = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        modositRadioGomb = new javax.swing.JRadioButton();
        torolRadioGomb = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        raktarLista = new javax.swing.JComboBox();
        keresGomb = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        hozzaadRadioGomb = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        nev = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        telefonszam = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();

        setBackground(new java.awt.Color(238, 238, 238));
        setPreferredSize(new java.awt.Dimension(1064, 401));

        KeszGomb.setBackground(new java.awt.Color(255, 140, 0));
        KeszGomb.setForeground(new java.awt.Color(255, 255, 255));
        KeszGomb.setText("KÉSZ");
        KeszGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeszGombActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 140, 113));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Raktár műveletek");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 267));

        modositRadioGomb.setBackground(new java.awt.Color(255, 255, 255));
        modositRadioGomb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        modositRadioGomb.setForeground(new java.awt.Color(0, 140, 113));
        modositRadioGomb.setText("Raktár adatmódosítás");
        modositRadioGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modositRadioGombActionPerformed(evt);
            }
        });

        torolRadioGomb.setBackground(new java.awt.Color(255, 255, 255));
        torolRadioGomb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        torolRadioGomb.setForeground(new java.awt.Color(0, 140, 113));
        torolRadioGomb.setText("Raktár törlés");
        torolRadioGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torolRadioGombActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 140, 113));
        jLabel7.setText("Raktár kiválasztás:");

        raktarLista.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                raktarListaItemStateChanged(evt);
            }
        });
        raktarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raktarListaActionPerformed(evt);
            }
        });
        raktarLista.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                raktarListaPropertyChange(evt);
            }
        });
        raktarLista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                raktarListaKeyPressed(evt);
            }
        });
        raktarLista.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                raktarListaVetoableChange(evt);
            }
        });

        keresGomb.setBackground(new java.awt.Color(255, 140, 0));
        keresGomb.setForeground(new java.awt.Color(255, 255, 255));
        keresGomb.setText("FRISSÍT");
        keresGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keresGombActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(keresGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modositRadioGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(raktarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(torolRadioGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modositRadioGomb)
                    .addComponent(torolRadioGomb))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(raktarLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(keresGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setPreferredSize(new java.awt.Dimension(500, 267));

        hozzaadRadioGomb.setBackground(new java.awt.Color(255, 255, 255));
        hozzaadRadioGomb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        hozzaadRadioGomb.setForeground(new java.awt.Color(0, 140, 113));
        hozzaadRadioGomb.setText("Új raktár hozzáadása");
        hozzaadRadioGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hozzaadRadioGombActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 140, 113));
        jLabel1.setText("Raktár megnevezés:");

        nev.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        nev.setPreferredSize(new java.awt.Dimension(125, 22));
        nev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nevActionPerformed(evt);
            }
        });
        nev.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ujRaktarAction(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 140, 113));
        jLabel2.setText("Raktár cím:");

        cim.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        cim.setPreferredSize(new java.awt.Dimension(125, 22));
        cim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ujRaktarAction(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 140, 113));
        jLabel3.setText("Raktár telefonszám:");

        telefonszam.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        telefonszam.setMinimumSize(new java.awt.Dimension(125, 22));
        telefonszam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ujRaktarAction(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 140, 113));
        jLabel4.setText("Raktár e-mail cím:");

        email.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        email.setPreferredSize(new java.awt.Dimension(125, 22));
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ujRaktarAction(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(hozzaadRadioGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(telefonszam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nev, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(hozzaadRadioGomb)
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telefonszam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(KeszGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(KeszGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void KeszGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeszGombActionPerformed

        try {
            String nev_ = nev.getText();
            String cim_ = cim.getText();
            String telefonszam_ = telefonszam.getText();
            String email_ = email.getText();

            if (hozzaadRadioGomb.isSelected() || modositRadioGomb.isSelected()) {

                if (nev_.equals("") || cim_.equals("") || telefonszam_.equals("") || email_.equals("")) {
                    JOptionPane.showMessageDialog(null, "Az adatok megadása kötelező!");
                    return;
                }
                if (telefonszam_.length() < 11 || telefonszam_.length() > 12 || telefonszam_.charAt(0) != '+' || telefonszam_.charAt(1) != '3' || telefonszam_.charAt(2) != '6') {
                    JOptionPane.showMessageDialog(null, "Telefoszám formátum +36202222222");
                    return;
                }
                if (!(email_.contains("@") && email_.contains("."))) {
                    JOptionPane.showMessageDialog(null, "Hibás e-mail cím!");
                    return;
                }
            }

            Raktár ujRaktar = new Raktár(nev_, cim_, telefonszam_, email_);

            if (hozzaadRadioGomb.isSelected()) {

                try {
                    db.ujRaktar(ujRaktar);
                    raktarLista.setModel(new DefaultComboBoxModel(db.getRaktarak()));
                    JOptionPane.showMessageDialog(null, "Raktár hozzáadva!");
                } catch (Exception ex) {
                    Logger.getLogger(DbKapcsolat.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Hibás adatbevitel!");
                }
            }

            if (modositRadioGomb.isSelected()) {
                Raktár modositandoRaktar = (Raktár) raktarLista.getSelectedItem();
                int modositandoRaktarId = modositandoRaktar.getRaktarId();
                ujRaktar.setRaktarId(modositandoRaktarId);
                db.modositRaktar(ujRaktar);

                raktarLista.setModel(new DefaultComboBoxModel(db.getRaktarak()));
                keresGomb.doClick();
            }
            if (torolRadioGomb.isSelected()) {
                Raktár torlendoRaktar = (Raktár) raktarLista.getSelectedItem();
                db.torolRaktar(torlendoRaktar);

                raktarLista.setModel(new DefaultComboBoxModel(db.getRaktarak()));
                keresGomb.doClick();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(keresGomb, "Hiba!");
        }


    }//GEN-LAST:event_KeszGombActionPerformed

    private void hozzaadRadioGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hozzaadRadioGombActionPerformed
        nev.setEditable(true);
        nev.setBackground(Color.WHITE);
        cim.setEditable(true);
        cim.setBackground(Color.WHITE);
        telefonszam.setEditable(true);
        telefonszam.setBackground(Color.WHITE);
        email.setEditable(true);
        email.setBackground(Color.WHITE);
        raktarLista.setEnabled(false);

        nev.setText("");
        cim.setText("");
        telefonszam.setText("");
        email.setText("");
    }//GEN-LAST:event_hozzaadRadioGombActionPerformed

    private void keresGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keresGombActionPerformed
        if (modositRadioGomb.isSelected()) {
            try {

                Raktár raktar = (Raktár) raktarLista.getSelectedItem();//db.lekerdezRaktar(nev.getText());
                //int cegId = termek.getBeszallitoId();
                nev.setText(raktar.getRaktarNev());
                cim.setText(raktar.getRaktarCim());
                telefonszam.setText(raktar.getRaktarTelefonSzam());
                email.setText(raktar.getRaktarEmailCim());

                nev.setEditable(true);
                nev.setBackground(Color.WHITE);
                cim.setEditable(true);
                cim.setBackground(Color.WHITE);
                telefonszam.setEditable(true);
                telefonszam.setBackground(Color.WHITE);
                email.setEditable(true);
                email.setBackground(Color.WHITE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Raktárlista üres!");
            }
        }
        if (torolRadioGomb.isSelected()) {
            try {
                Raktár raktar = (Raktár) raktarLista.getSelectedItem(); //db.lekerdezRaktar(nev.getText());
                nev.setText(raktar.getRaktarNev());
                cim.setText(raktar.getRaktarCim());
                telefonszam.setText(raktar.getRaktarTelefonSzam());
                email.setText(raktar.getRaktarEmailCim());

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Raktárlista üres!");

                nev.setText("");
                cim.setText("");
                telefonszam.setText("");
                email.setText("");
            }
        }
    }//GEN-LAST:event_keresGombActionPerformed

    private void modositRadioGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modositRadioGombActionPerformed
        nev.setEditable(false);
        nev.setBackground(Color.LIGHT_GRAY);
        cim.setEditable(false);
        cim.setBackground(Color.LIGHT_GRAY);
        telefonszam.setEditable(false);
        telefonszam.setBackground(Color.LIGHT_GRAY);
        email.setEditable(false);
        email.setBackground(Color.LIGHT_GRAY);
        raktarLista.setEnabled(true);

        keresGomb.doClick();
    }//GEN-LAST:event_modositRadioGombActionPerformed

    private void torolRadioGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torolRadioGombActionPerformed
        nev.setEditable(false);
        nev.setBackground(Color.LIGHT_GRAY);
        cim.setEditable(false);
        cim.setBackground(Color.LIGHT_GRAY);
        telefonszam.setEditable(false);
        telefonszam.setBackground(Color.LIGHT_GRAY);
        email.setEditable(false);
        email.setBackground(Color.LIGHT_GRAY);
        raktarLista.setEnabled(true);

        keresGomb.doClick();
    }//GEN-LAST:event_torolRadioGombActionPerformed

    private void ujRaktarAction(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ujRaktarAction
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            KeszGomb.doClick();

        }
    }//GEN-LAST:event_ujRaktarAction

    private void raktarListaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_raktarListaKeyPressed
        /*  if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
         //  System.out.println("jo");
         if (modositRadioGomb.isSelected() || torolRadioGomb.isSelected()) {
         keresGomb.doClick();
         }
         }*/
    }//GEN-LAST:event_raktarListaKeyPressed

    private void raktarListaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_raktarListaItemStateChanged
        //System.out.println("jo");
    }//GEN-LAST:event_raktarListaItemStateChanged

    private void raktarListaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_raktarListaPropertyChange
        // System.out.println("jo");
    }//GEN-LAST:event_raktarListaPropertyChange

    private void raktarListaVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_raktarListaVetoableChange

    }//GEN-LAST:event_raktarListaVetoableChange

    private void raktarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raktarListaActionPerformed
        if (modositRadioGomb.isSelected() || torolRadioGomb.isSelected()) {
            keresGomb.doClick();
        }
    }//GEN-LAST:event_raktarListaActionPerformed

    private void nevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nevActionPerformed

    public JComboBox getRaktarListaComboBox() {
        return this.raktarLista;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KeszGomb;
    private javax.swing.JTextField cim;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton hozzaadRadioGomb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton keresGomb;
    private javax.swing.JRadioButton modositRadioGomb;
    private javax.swing.JTextField nev;
    private javax.swing.ButtonGroup radioGombok;
    private javax.swing.JComboBox raktarLista;
    private javax.swing.JTextField telefonszam;
    private javax.swing.JRadioButton torolRadioGomb;
    // End of variables declaration//GEN-END:variables
}
