
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.text.JTextComponent;
import newpackage.DbKapcsolat;
import newpackage.Raktár;
import newpackage.Termék;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kicsi
 */
public class RaktarkoziAtvezetes extends javax.swing.JPanel {

    private DbKapcsolat db;
    private Raktár kijeloltCelRaktar;
    private Termék kijeloltTermek;
    private Raktár kijeloltStartRaktar;
    private int startRaktarId;
    private int celRaktarId;
    private int termekId;

    public RaktarkoziAtvezetes() {
        initComponents();

        db = frame.getDbKapcsolat();

        startRaktarLista.setEditable(true);
        AutoCompleteDecorator.decorate(startRaktarLista);

    }

    public JComboBox getStartRaktarComboBox() {
        return this.startRaktarLista;
    }

    public JComboBox getCelRaktarComboBox() {
        return this.celRaktarLista;
    }

    public JComboBox getTermekListaComboBox() {
        return this.termekLista;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        startRaktarLista = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        termekLista = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        aktualisMennyiseg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kuldendoMennyiseg = new javax.swing.JTextField();
        keresGomb = new javax.swing.JButton();
        termekKeresGomb = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        celRaktarLista = new javax.swing.JComboBox();
        atvezetGomb = new javax.swing.JButton();

        setBackground(new java.awt.Color(238, 238, 238));

        jPanel1.setBackground(new java.awt.Color(0, 140, 113));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Raktárközi átvezetés");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 140, 113));
        jLabel5.setText("Kiindulási Raktár:");

        startRaktarLista.setEditable(true);
        startRaktarLista.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        startRaktarLista.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                startRaktarListaItemStateChanged(evt);
            }
        });
        startRaktarLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startRaktarListaMouseClicked(evt);
            }
        });
        startRaktarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startRaktarListaActionPerformed(evt);
            }
        });
        startRaktarLista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                startRaktarListaKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 140, 113));
        jLabel3.setText("Termék kiválasztása:");

        termekLista.setEditable(true);
        termekLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termekListaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 140, 113));
        jLabel6.setText("Aktuális termék mennyiség:");

        aktualisMennyiseg.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        aktualisMennyiseg.setForeground(new java.awt.Color(255, 140, 0));
        aktualisMennyiseg.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 140, 113));
        jLabel4.setText("Átvezetett termék mennyiség:");

        kuldendoMennyiseg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        keresGomb.setBackground(new java.awt.Color(255, 140, 0));
        keresGomb.setForeground(new java.awt.Color(255, 255, 255));
        keresGomb.setText("FRISSÍT");
        keresGomb.setToolTipText("");
        keresGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keresGombActionPerformed(evt);
            }
        });

        termekKeresGomb.setBackground(new java.awt.Color(255, 140, 0));
        termekKeresGomb.setForeground(new java.awt.Color(255, 255, 255));
        termekKeresGomb.setText("FRISSÍT");
        termekKeresGomb.setToolTipText("");
        termekKeresGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termekKeresGombActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(41, 41, 41)
                                .addComponent(aktualisMennyiseg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(keresGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(termekLista, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(termekKeresGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(30, 30, 30)
                                                .addComponent(startRaktarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 14, Short.MAX_VALUE)))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(49, 49, 49)
                        .addComponent(kuldendoMennyiseg, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(startRaktarLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(termekKeresGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(termekLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(keresGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(aktualisMennyiseg, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(kuldendoMennyiseg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 140, 113));
        jLabel2.setText("Cél Raktár:");

        celRaktarLista.setEditable(true);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(celRaktarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(celRaktarLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        atvezetGomb.setBackground(new java.awt.Color(255, 140, 0));
        atvezetGomb.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        atvezetGomb.setForeground(new java.awt.Color(255, 255, 255));
        atvezetGomb.setText("ÁTVEZET");
        atvezetGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atvezetGombActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(atvezetGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(atvezetGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void startRaktarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startRaktarListaActionPerformed
        termekKeresGomb.doClick();
        keresGomb.doClick();
    }//GEN-LAST:event_startRaktarListaActionPerformed

    private void startRaktarListaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_startRaktarListaKeyPressed

    }//GEN-LAST:event_startRaktarListaKeyPressed

    private void startRaktarListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startRaktarListaMouseClicked
        // termekKeresGomb.doClick();
    }//GEN-LAST:event_startRaktarListaMouseClicked

    private void startRaktarListaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_startRaktarListaItemStateChanged


    }//GEN-LAST:event_startRaktarListaItemStateChanged

    private void atvezetGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atvezetGombActionPerformed

        try {
            kijeloltCelRaktar = (Raktár) celRaktarLista.getSelectedItem();
            celRaktarId = kijeloltCelRaktar.getRaktarId();

            int hanyDb = Integer.parseInt(kuldendoMennyiseg.getText());
            db.raktarkoziAtvezetes(startRaktarId, celRaktarId, termekId, hanyDb);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Adja meg a mennyiséget");
        }
        
        keresGomb.doClick();


    }//GEN-LAST:event_atvezetGombActionPerformed

    private void termekKeresGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termekKeresGombActionPerformed

        if (!(startRaktarLista.getSelectedItem().getClass() == String.class)) {
            kijeloltStartRaktar = (Raktár) startRaktarLista.getSelectedItem();

            startRaktarId = kijeloltStartRaktar.getRaktarId();

            //raktarban levő termek lista szűrése
            db.raktarTermekLista(startRaktarId);
            Vector<Termék> termekek = db.getTermekekAdottRaktarban();
            termekLista.setModel(new DefaultComboBoxModel(termekek));

            //cél raktár szűrése start raktara nelkul
            Vector<Raktár> celRaktarak = (Vector<Raktár>) db.getRaktarak().clone();
            celRaktarak.remove(kijeloltStartRaktar);
            celRaktarLista.setModel(new DefaultComboBoxModel(celRaktarak));

        }


    }//GEN-LAST:event_termekKeresGombActionPerformed

    private void termekListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termekListaActionPerformed

        keresGomb.doClick();

    }//GEN-LAST:event_termekListaActionPerformed

    private void keresGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keresGombActionPerformed
        Object ellenorzesTermek = termekLista.getSelectedItem();
        if (ellenorzesTermek != null) {
            kijeloltTermek = (Termék) termekLista.getSelectedItem();
            termekId = kijeloltTermek.getTermekId();

            int aktualisDb = db.aktualisTermekMennyisegRaktarban(kijeloltStartRaktar, kijeloltTermek);
            aktualisMennyiseg.setText(String.valueOf(aktualisDb));
        } else {
            aktualisMennyiseg.setText("");
        }
    }//GEN-LAST:event_keresGombActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aktualisMennyiseg;
    private javax.swing.JButton atvezetGomb;
    private javax.swing.JComboBox celRaktarLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton keresGomb;
    private javax.swing.JTextField kuldendoMennyiseg;
    private javax.swing.JComboBox startRaktarLista;
    private javax.swing.JButton termekKeresGomb;
    private javax.swing.JComboBox termekLista;
    // End of variables declaration//GEN-END:variables
}
