/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adatbáziskliens;

import adatbáziskapcsolat.DbKapcsolat;
import adatbáziskapcsolat.Raktár;
import adatbáziskapcsolat.Termék;
import java.util.Vector;
import javax.swing.JFrame;

/**
 *
 * @author kicsi
 */
public class RaktarkoziAtvezetes extends javax.swing.JDialog {

    /**
     * Creates new form RaktarkoziAtvezetes
     */
    public RaktarkoziAtvezetes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        db = ((Keszletnyilvantarto) parent).getDbKapcsolat();
        frame = ((Keszletnyilvantarto) parent);
        startRaktarLista.setListData(db.getRaktarak());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        startRaktarLista = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        termekLista = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        celRaktarLista = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        atvezetGomb = new javax.swing.JButton();
        kuldendoMennyiseg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        aktualisMennyiseg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Raktárközi Átvezetés");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Raktárközi átvezetés");

        startRaktarLista.setToolTipText("");
        startRaktarLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startRaktarListaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(startRaktarLista);

        termekLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                termekListaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(termekLista);

        jScrollPane3.setViewportView(celRaktarLista);

        jLabel2.setText("Aktuális mennyiség:");

        atvezetGomb.setText("->");
        atvezetGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atvezetGombActionPerformed(evt);
            }
        });

        kuldendoMennyiseg.setText("0");

        jLabel3.setText("Küldendő mennyiség:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(aktualisMennyiseg, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(kuldendoMennyiseg, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                        .addGap(19, 19, 19)
                        .addComponent(atvezetGomb)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(atvezetGomb)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kuldendoMennyiseg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aktualisMennyiseg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atvezetGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atvezetGombActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atvezetGombActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        frame.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void startRaktarListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startRaktarListaMouseClicked
        kijeloltRaktar=(Raktár)startRaktarLista.getSelectedValue();
        int raktarId=kijeloltRaktar.getRaktarId();        
        db.raktarTermekLista(raktarId);
        Vector<Termék> termekek=db.getTermekekAdottRaktarban();
        termekLista.setListData(termekek);        
    }//GEN-LAST:event_startRaktarListaMouseClicked

    private void termekListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_termekListaMouseClicked
        kijeloltTermek=(Termék)termekLista.getSelectedValue();
        int aktualisDb=db.aktualisTermekMennyisegRaktarban(kijeloltRaktar,kijeloltTermek);
        aktualisMennyiseg.setText(String.valueOf(aktualisDb));
        
    }//GEN-LAST:event_termekListaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RaktarkoziAtvezetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RaktarkoziAtvezetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RaktarkoziAtvezetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RaktarkoziAtvezetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RaktarkoziAtvezetes dialog = new RaktarkoziAtvezetes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aktualisMennyiseg;
    private javax.swing.JButton atvezetGomb;
    private javax.swing.JList celRaktarLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField kuldendoMennyiseg;
    private javax.swing.JList startRaktarLista;
    private javax.swing.JList termekLista;
    // End of variables declaration//GEN-END:variables
    protected DbKapcsolat db;
    protected JFrame frame;
    private Raktár kijeloltRaktar;
    private Termék kijeloltTermek;
}
